### ISSUE TITLE
Fieldset won't remember width after save

### ISSUE THREAD

**Issue by matjazpotocnik** [Toutouwai/TemplateFieldWidths#3]
Hi, Robin, you might want to look at this: https://github.com/processwire/processwire-issues/issues/994

**Comment by Toutouwai** [comment]
Thanks for the report. You don't actually need to save the Edit Template form after changing a field width using a core input, but it's not an unlikely thing for someone to do so I've made a change to when widths in the Template Field Width inputfield get saved.

More info in the support topic: https://processwire.com/talk/topic/20371-template-field-widths/?do=findComment&comment=192382

**Comment by matjazpotocnik** [comment]
Thanks, it's working now.
